# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import editor_md.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='标题')),
                ('content', editor_md.models.EditorMdField(blank=True, verbose_name='文章内容')),
            ],
        ),
    ]
